services:
  bifrost:
    image: maximhq/bifrost:v2.2.2
    restart: unless-stopped

    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      LOG_LEVEL: info
      LOG_STYLE: json
      BIFROST_ENCRYPTION_KEY: ${BIFROST_ENCRYPTION_KEY}
      BIFROST_SETUP_TOKEN: ${BIFROST_SETUP_TOKEN}

    volumes:
      - bifrost-data:/app/data

    networks:
      - dokploy-network

networks:
  default:
    external: true
    name: dokploy-network

  dokploy-network:
    external: true

volumes:
  bifrost-data:
    driver: local