services:

  ocis:
    image: owncloud/ocis:8.2.0
    restart: always
    command:
      - server
    environment:
      OCIS_URL: https://${OCIS_DOMAIN}

      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_MACHINE_AUTH_API_KEY}

      START_ADDITIONAL_SERVICES: notifications

    volumes:
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
      - ocis-apps:/var/lib/ocis/apps

    expose:
      - "9200"

    networks:
      - dokploy-network

    labels:
      traefik.enable: "true"
      traefik.docker.network: "dokploy-network"

      traefik.http.routers.lab-owncloud-ocis.rule: "Host(`${OCIS_DOMAIN}`)"
      traefik.http.routers.lab-owncloud-ocis.entrypoints: "websecure"
      traefik.http.routers.lab-owncloud-ocis.tls: "true"
      traefik.http.routers.lab-owncloud-ocis.service: "lab-owncloud-ocis"

      traefik.http.services.lab-owncloud-ocis.loadbalancer.server.port: "9200"


  collaboration:
    image: owncloud/ocis:8.2.0
    restart: always

    depends_on:
      ocis:
        condition: service_started
      collabora:
        condition: service_healthy

    command:
      - collaboration
      - server

    environment:
      OCIS_URL: https://${OCIS_DOMAIN}

      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET}
      OCIS_REVA_GATEWAY: ${OCIS_REVA_GATEWAY}

      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300

      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: ocis:9233

      COLLABORATION_WOPI_SRC: https://${WOPISERVER_DOMAIN}

      COLLABORATION_APP_NAME: Collabora
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_APP_ADDR: https://${COLLABORA_DOMAIN}
      COLLABORATION_APP_ICON: https://${COLLABORA_DOMAIN}/favicon.ico

      COLLABORATION_APP_INSECURE: "false"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "false"

      COLLABORATION_WOPI_SECRET: ${COLLABORATION_WOPI_SECRET}

      COLLABORATION_LOG_LEVEL: info

    volumes:
      - ocis-config:/etc/ocis

    expose:
      - "9300"
      - "9301"

    networks:
      - dokploy-network


  collabora:
    image: collabora/code:25.04.7.3.1
    restart: always

    entrypoint:
      - /bin/sh

    command:
      - -c
      - |
        coolconfig generate-proof-key
        exec /start-collabora-online.sh

    environment:
      DONT_GEN_SSL_CERT: "YES"

      extra_params: >-
        --o:ssl.enable=false
        --o:ssl.ssl_verification=false
        --o:ssl.termination=true
        --o:welcome.enable=false
        --o:net.frame_ancestors=https://${OCIS_DOMAIN}

      username: ${COLLABORA_ADMIN_USERNAME}
      password: ${COLLABORA_ADMIN_PASSWORD}

    cap_add:
      - MKNOD

    expose:
      - "9980"

    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9980/hosting/discovery
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

    networks:
      - dokploy-network

    labels:
      traefik.enable: "true"
      traefik.docker.network: "dokploy-network"

      traefik.http.routers.lab-owncloud-collabora.rule: "Host(`${COLLABORA_DOMAIN}`)"
      traefik.http.routers.lab-owncloud-collabora.entrypoints: "websecure"
      traefik.http.routers.lab-owncloud-collabora.tls: "true"
      traefik.http.routers.lab-owncloud-collabora.service: "lab-owncloud-collabora"

      traefik.http.services.lab-owncloud-collabora.loadbalancer.server.port: "9980"


volumes:
  ocis-config:
    name: owncloud-ocis-config

  ocis-data:
    name: owncloud-ocis-data

  ocis-apps:
    name: owncloud-ocis-apps


networks:
  dokploy-network:
    external: true