services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch-plugins.yml:/usr/share/elasticsearch/config/elasticsearch-plugins.yml

    networks:
      - dokploy-network

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:

  elasticsearch_data:
    name: lab-elasticsearch_elasticsearch_data


networks:

  default:
    name: dokploy-network
    external: true

  dokploy-network:
    name: dokploy-network
    external: true