services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"

    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
      - /etc/dokploy/adguard-certs:/etc/adguard-certs:ro

    labels:
      - traefik.http.services.lab-adguard-4ynnux-29-websecure.loadbalancer.server.scheme=https

    networks:
      dokploy-network:
        ipv4_address: 10.0.1.150

volumes:
  adguardhome-work:
    name: lab-adguard-4ynnux_adguardhome-work

  adguardhome-conf:
    name: lab-adguard-4ynnux_adguardhome-conf

networks:
  default:
    name: dokploy-network
    external: true

  dokploy-network:
    name: dokploy-network
    external: true